-- ddl_oracle.sql
-- Ajustar: reemplaza SCHEMA_USER por tu usuario si es necesario

-- Uso de IDENTITY columns (Oracle 12c+)
CREATE TABLE institucion (
  id_institucion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(200) NOT NULL
);

CREATE TABLE sede (
  id_sede NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_institucion NUMBER NOT NULL,
  nombre VARCHAR2(200),
  direccion VARCHAR2(400),
  es_principal NUMBER(1) DEFAULT 0,
  CONSTRAINT fk_sede_institucion FOREIGN KEY (id_institucion) REFERENCES institucion(id_institucion)
);

CREATE TABLE programa (
  id_programa NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  tipo VARCHAR2(50) NOT NULL -- e.g. INSIDECLASSROOM / OUTSIDECLASSROOM
);

CREATE TABLE periodo (
  id_periodo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_programa NUMBER NOT NULL,
  fecha_inicio DATE,
  fecha_final DATE,
  descripcion VARCHAR2(200),
  CONSTRAINT fk_periodo_programa FOREIGN KEY (id_programa) REFERENCES programa(id_programa)
);

CREATE TABLE componente_nota (
  id_componente NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_programa NUMBER NOT NULL,
  nombre VARCHAR2(100),
  porcentaje NUMBER(5,2),
  CONSTRAINT fk_comp_programa FOREIGN KEY (id_programa) REFERENCES programa(id_programa)
);

CREATE TABLE aula (
  id_aula NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_sede NUMBER NOT NULL,
  id_programa NUMBER NOT NULL,
  grado VARCHAR2(20),
  nombre VARCHAR2(200),
  CONSTRAINT fk_aula_sede FOREIGN KEY (id_sede) REFERENCES sede(id_sede),
  CONSTRAINT fk_aula_programa FOREIGN KEY (id_programa) REFERENCES programa(id_programa)
);

CREATE TABLE horario (
  id_horario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_aula NUMBER NOT NULL,
  dia_semana VARCHAR2(20), -- LUNES, MARTES...
  hora_inicio VARCHAR2(5), -- '06:00'
  hora_fin VARCHAR2(5),
  duracion_minutos NUMBER,
  CONSTRAINT fk_horario_aula FOREIGN KEY (id_aula) REFERENCES aula(id_aula)
);

-- Persona y usuario
CREATE TABLE persona (
  id_persona NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(200),
  tipo_documento VARCHAR2(50),
  numero_documento VARCHAR2(100),
  correo VARCHAR2(200)
);

CREATE TABLE usuario (
  id_usuario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_persona NUMBER UNIQUE,
  username VARCHAR2(100) UNIQUE,
  password_hash VARCHAR2(400),
  rol VARCHAR2(30),
  CONSTRAINT fk_usuario_persona FOREIGN KEY (id_persona) REFERENCES persona(id_persona)
);

-- Tutor (hereda persona)
CREATE TABLE tutor (
  id_tutor NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_persona NUMBER NOT NULL UNIQUE,
  fecha_contrato DATE,
  CONSTRAINT fk_tutor_persona FOREIGN KEY (id_persona) REFERENCES persona(id_persona)
);

-- Estudiante
CREATE TABLE estudiante (
  id_estudiante NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_persona NUMBER NOT NULL,
  id_aula NUMBER, -- aula actual
  grado VARCHAR2(20),
  score_inicial NUMBER,
  score_final NUMBER,
  CONSTRAINT fk_estudiante_persona FOREIGN KEY (id_persona) REFERENCES persona(id_persona),
  CONSTRAINT fk_estudiante_aula FOREIGN KEY (id_aula) REFERENCES aula(id_aula)
);

-- Tabla para historial de cambios de aula del estudiante
CREATE TABLE registro_cambio_aula (
  id_registro NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_estudiante NUMBER NOT NULL,
  id_aula_origen NUMBER,
  id_aula_destino NUMBER,
  fecha DATE DEFAULT SYSDATE,
  motivo VARCHAR2(200),
  CONSTRAINT fk_rca_estudiante FOREIGN KEY (id_estudiante) REFERENCES estudiante(id_estudiante),
  CONSTRAINT fk_rca_aula_origen FOREIGN KEY (id_aula_origen) REFERENCES aula(id_aula),
  CONSTRAINT fk_rca_aula_destino FOREIGN KEY (id_aula_destino) REFERENCES aula(id_aula)
);

-- Asignacion Tutor <-> Aula (historial)
CREATE TABLE asignacion_tutor_aula (
  id_asignacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_tutor NUMBER NOT NULL,
  id_aula NUMBER NOT NULL,
  fecha_inicio DATE DEFAULT SYSDATE,
  fecha_fin DATE NULL,
  CONSTRAINT fk_ata_tutor FOREIGN KEY (id_tutor) REFERENCES tutor(id_tutor),
  CONSTRAINT fk_ata_aula FOREIGN KEY (id_aula) REFERENCES aula(id_aula)
);

-- Asignacion Horario <-> Aula (historial)
CREATE TABLE asignacion_horario_aula (
  id_asg_horario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_horario NUMBER NOT NULL,
  id_aula NUMBER NOT NULL,
  fecha_inicio DATE DEFAULT SYSDATE,
  fecha_fin DATE NULL,
  CONSTRAINT fk_asha_horario FOREIGN KEY (id_horario) REFERENCES horario(id_horario),
  CONSTRAINT fk_asha_aula FOREIGN KEY (id_aula) REFERENCES aula(id_aula)
);

-- Festivos y motivos
CREATE TABLE festivo (
  id_festivo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  fecha DATE UNIQUE,
  descripcion VARCHAR2(200)
);

CREATE TABLE motivo (
  id_motivo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(200)
);

-- Asistencia del aula tomada por tutor (incluye reposicion)
CREATE TABLE asistencia_aula_tutor (
  id_asistencia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_aula NUMBER NOT NULL,
  id_tutor NUMBER NOT NULL,
  id_horario NUMBER,
  fecha DATE NOT NULL,
  se_dio NUMBER(1) DEFAULT 1, -- 1 = se dictó, 0 = no se dictó
  id_motivo NUMBER NULL,
  id_asistencia_reposicion NUMBER NULL, -- referencia a otra fila aquí
  CONSTRAINT fk_aatt_aula FOREIGN KEY (id_aula) REFERENCES aula(id_aula),
  CONSTRAINT fk_aatt_tutor FOREIGN KEY (id_tutor) REFERENCES tutor(id_tutor),
  CONSTRAINT fk_aatt_horario FOREIGN KEY (id_horario) REFERENCES horario(id_horario),
  CONSTRAINT fk_aatt_motivo FOREIGN KEY (id_motivo) REFERENCES motivo(id_motivo),
  CONSTRAINT fk_aatt_reposicion FOREIGN KEY (id_asistencia_reposicion) REFERENCES asistencia_aula_tutor(id_asistencia)
);

-- Asistencia por estudiante (detalle)
CREATE TABLE asistencia_aula_estudiante (
  id_asist_est NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_asistencia NUMBER NOT NULL,
  id_estudiante NUMBER NOT NULL,
  presente NUMBER(1) DEFAULT 0,
  CONSTRAINT fk_aae_asistencia FOREIGN KEY (id_asistencia) REFERENCES asistencia_aula_tutor(id_asistencia),
  CONSTRAINT fk_aae_estudiante FOREIGN KEY (id_estudiante) REFERENCES estudiante(id_estudiante)
);

-- Notas
CREATE TABLE nota (
  id_nota NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_estudiante NUMBER NOT NULL,
  id_periodo NUMBER NOT NULL,
  id_componente NUMBER NOT NULL,
  id_tutor NUMBER NOT NULL, -- quien registra
  valor NUMBER(6,2),
  fecha_registro DATE DEFAULT SYSDATE,
  CONSTRAINT fk_nota_estudiante FOREIGN KEY (id_estudiante) REFERENCES estudiante(id_estudiante),
  CONSTRAINT fk_nota_periodo FOREIGN KEY (id_periodo) REFERENCES periodo(id_periodo),
  CONSTRAINT fk_nota_componente FOREIGN KEY (id_componente) REFERENCES componente_nota(id_componente),
  CONSTRAINT fk_nota_tutor FOREIGN KEY (id_tutor) REFERENCES tutor(id_tutor)
);

-- Índices sugeridos
CREATE INDEX idx_estudiante_aula ON estudiante(id_aula);
CREATE INDEX idx_asistencia_fecha ON asistencia_aula_tutor(fecha);
CREATE INDEX idx_asist_estudiante_est ON asistencia_aula_estudiante(id_estudiante);
