-- seed_full.sql
INSERT INTO INSTITUCION (NOMBRE) VALUES ('Instituto Demo');
INSERT INTO SEDE (NOMBRE_SEDE, DIRECCION, ID_INSTITUCION) VALUES ('Sede Central', 'Calle Demo 123', 1);
INSERT INTO PROGRAMA (TIPO) VALUES ('PRESENCIAL');

-- Personas
INSERT INTO PERSONA (NOMBRE, ROL) VALUES ('Juan Perez', 'Tutor');
INSERT INTO PERSONA (NOMBRE, ROL) VALUES ('María Gómez', 'Estudiante');
INSERT INTO PERSONA (NOMBRE, ROL) VALUES ('Admin Demo', 'Administrador');

-- Usuarios (CONTRASENA en claro para pruebas)
INSERT INTO USUARIO (CONTRASENA, ID_PERSONA) VALUES ('1', 1); -- contraseña = '1' (puedes usar id_persona)
INSERT INTO USUARIO (CONTRASENA, ID_PERSONA) VALUES ('2', 2);
INSERT INTO USUARIO (CONTRASENA, ID_PERSONA) VALUES ('3', 3);

-- Tutor (vinculado a persona 1)
INSERT INTO TUTOR (ID_PERSONA) VALUES (1);

-- Aula (asigna ID_TUTOR más adelante)
INSERT INTO AULA (GRADO, ID_SEDE, ID_PROGRAMA, ID_TUTOR) VALUES ('10', 1, 1, 1);

-- Estudiante (usa NOMBRE duplicado en ESTUDIANTE)
INSERT INTO ESTUDIANTE (TIPO_DOCUMENTO, NOMBRE, GRADO, SCORE_INICIAL, ID_AULA) VALUES ('CC', 'María Gómez', '10', 80, 1);

-- Periodo, componente y nota de ejemplo
INSERT INTO PERIODO (FECHA_INICIO, FECHA_FIN, ID_PROGRAMA) VALUES (TO_DATE('2025-01-01','YYYY-MM-DD'), TO_DATE('2025-06-30','YYYY-MM-DD'), 1);
INSERT INTO COMPONENTE (NOMBRE, PORCENTAJE, ID_PROGRAMA) VALUES ('Parcial 1', 30, 1);

INSERT INTO NOTA (VALOR, ID_ESTUDIANTE, ID_PERIODO, ID_COMPONENTE, ID_TUTOR) VALUES (85, 1, 1, 1, 1);

COMMIT;
